local tsconfig = require "nvim-treesitter.configs"
tsconfig.setup {
  ensure_installed = {
    "c",
    "lua",
    "rust",
    "html",
    "javascript",
    "css",
    "python",
    "latex",
    "json",
    "dockerfile",
    "cmake",
    "make",
  },
  highlight = { enable = true },
  -- indent = { enable = true },
  autopairs = { enable = true },
  autotag = { enable = true },
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = "<CR>",
      scope_incremental = "<CR>",
      node_incremental = "<S-CR>",
      node_decremental = ";",
    },
  },
  additional_vim_regex_highlighting = true,
  context_commentstring = { -- NOTE: Assuming 'JoosepAlviste/nvim-ts-context-commentstring' is installed!
    enable = true,
  },
  textobjects = {
    select = {
      enable = true,
      -- WARN: This may clash with current keymaps. not sure yet but will find out
      keymaps = {
        ["af"] = "@function.outer",
        ["if"] = "@function.inner",
        ["ac"] = "@class.outer",
        ["ic"] = "@class.inner",
        ["ae"] = "@else.outer",
        ["ie"] = "@else.inner",
        ["al"] = "@loop.outer",
        ["il"] = "@loop.inner",
        ["ad"] = "@do.outer",
        ["id"] = "@do.inner",
        ["ah"] = "@while.outer",
        ["ih"] = "@while.inner",
        ["as"] = "@switch.outer",
        ["is"] = "@switch.inner",
        ["aa"] = "@case.outer",
        ["ia"] = "@case.inner",
        ["ab"] = "@block.outer",
        ["ib"] = "@block.inner",
        ["ao"] = "@operator.outer",
        ["io"] = "@operator.inner",
        ["at"] = "@type.outer",
        ["it"] = "@type.inner",
        ["av"] = "@variable.outer",
        ["iv"] = "@variable.inner",
        ["ax"] = "@extends.outer",
        ["ix"] = "@extends.inner",
        ["ay"] = "@implements.outer",
        ["iy"] = "@implements.inner",
        ["az"] = "@throws.outer",
        ["iz"] = "@throws.inner",
        ["ba"] = "@array.outer",
        ["ja"] = "@array.inner",
        ["bb"] = "@object.outer",
        ["jb"] = "@object.inner",
        ["bc"] = "@interface.outer",
        ["jc"] = "@interface.inner",
        ["bd"] = "@enum.outer",
        ["jd"] = "@enum.inner",
        ["be"] = "@enum_value.outer",
        ["je"] = "@enum_value.inner",
        ["bf"] = "@annotation.outer",
        ["jf"] = "@annotation.inner",
        ["bg"] = "@ann",
      },
    },
  },
}
